#!/bin/bash
echo "School" 
*c
root@0ebcc3bd5bc8:/alx-pre_course/0x01-git/bash# git add .
root@0ebcc3bd5bc8:/alx-pre_course/0x01-git/bash# git commit -m  “Starting to code today, so cool”
root@0ebcc3bd5bc8:/alx-pre_course/0x01-git/bash# git push
